/*
 * NewBeanForm.java
 *
 * Created on 28 mars 2008, 17:47
 */

package LanceurRayon.IHM.Arbre;

import javax.swing.JPopupMenu;

/**
 *
 * @author  Lecrubier
 */
public class ArbreXMLPopupMenu extends JPopupMenu {
	
	/** Creates new form BeanForm */
	public ArbreXMLPopupMenu() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemSupprimer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        ItemModifier = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        ItemCouper = new javax.swing.JMenuItem();
        ItemCopier = new javax.swing.JMenuItem();
        ItemColler = new javax.swing.JMenuItem();

        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(LanceurRayon.LanceurRayonApp.class).getContext().getActionMap(ArbreXMLPopupMenu.class, this);
        ItemSupprimer.setAction(actionMap.get("supprimer")); // NOI18N
        ItemSupprimer.setName("ItemSupprimer"); // NOI18N
        add(ItemSupprimer);

        jSeparator1.setName("jSeparator1"); // NOI18N
        add(jSeparator1);

        ItemModifier.setAction(actionMap.get("editer")); // NOI18N
        ItemModifier.setName("ItemModifier"); // NOI18N
        add(ItemModifier);

        jSeparator2.setName("jSeparator2"); // NOI18N
        add(jSeparator2);

        ItemCouper.setAction(actionMap.get("couper")); // NOI18N
        ItemCouper.setName("ItemCouper"); // NOI18N
        add(ItemCouper);

        ItemCopier.setAction(actionMap.get("copier")); // NOI18N
        ItemCopier.setName("ItemCopier"); // NOI18N
        add(ItemCopier);

        ItemColler.setAction(actionMap.get("coller")); // NOI18N
        ItemColler.setName("ItemColler"); // NOI18N
        add(ItemColler);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemColler;
    private javax.swing.JMenuItem ItemCopier;
    private javax.swing.JMenuItem ItemCouper;
    private javax.swing.JMenuItem ItemModifier;
    private javax.swing.JMenuItem ItemSupprimer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
	
}
