/*
 * FenetreAPropos.java
 *
 * Created on 5 mars 2008, 20:35
 */

package LanceurRayon.IHM;

import LanceurRayon.LanceurRayonApp;
import java.io.IOException;

/**
 *
 * @author  Lecrubier
 */
public class FenetreAPropos extends javax.swing.JFrame {
	
	/** Creates new form FenetreAPropos */
	public FenetreAPropos() {
		initComponents();
		
        java.net.URL helpURL = FenetreAPropos.class.getResource(
                                        "resources/about.html");
        if (helpURL != null) {
            try {
                TexteAPropos.setPage(helpURL);
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: about.html");
        }

	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAPropos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TexteAPropos = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(LanceurRayon.LanceurRayonApp.class).getContext().getResourceMap(FenetreAPropos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 300, 200));
        setForeground(resourceMap.getColor("Form.foreground")); // NOI18N
        setIconImage(LanceurRayonApp.getInstance(LanceurRayon.LanceurRayonApp.class).getContext().getResourceMap(LanceurRayonApp.class).getImageIcon("Application.icon").getImage());
        setName("Form"); // NOI18N
        setResizable(false);

        PanelAPropos.setBackground(resourceMap.getColor("PanelAPropos.background")); // NOI18N
        PanelAPropos.setName("PanelAPropos"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        TexteAPropos.setEditable(false);
        TexteAPropos.setText(resourceMap.getString("TexteAPropos.text")); // NOI18N
        TexteAPropos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        TexteAPropos.setName("TexteAPropos"); // NOI18N
        jScrollPane1.setViewportView(TexteAPropos);

        javax.swing.GroupLayout PanelAProposLayout = new javax.swing.GroupLayout(PanelAPropos);
        PanelAPropos.setLayout(PanelAProposLayout);
        PanelAProposLayout.setHorizontalGroup(
            PanelAProposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        PanelAProposLayout.setVerticalGroup(
            PanelAProposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAPropos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAPropos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAPropos;
    private javax.swing.JTextPane TexteAPropos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
	
}
